
		//FOR TEST - REPLACE WITH IMPORTED CSV & CONFIGURE TO USE WITH CSV
		//LISTINGS ARE PLACEHOLDERS FOR DEMO PURPOSES & DONT REFLECT THE BRANDS USED
var techList = [
		{TECH:"Java", CAT:"", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"", EVALUATE:"", TRIAL:"", ADOPT:"", HOLD:"y", DATE:"14-6-2015", DETAILS:"Coding - stable, useful"},
		{TECH:"Ruby", CAT:"app", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"", EVALUATE:"", TRIAL:"", ADOPT:"", HOLD:"", DATE:"2-7-2016", DETAILS:"Coding - new use"},
		{TECH:"Swift", CAT:"", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"", EVALUATE:"", TRIAL:"", ADOPT:"", HOLD:"", DATE:"2-8-2014", DETAILS:"Animation software - replacing with CCS3, SVG..., no new builds"},
		{TECH:"ClickMeeting", CAT:"", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"", EVALUATE:"", TRIAL:"", ADOPT:"", HOLD:"", DATE:"14-6-2017", DETAILS:"video conferencing - useful"},
		{TECH:"Citrix Grasshopper", CAT:"", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"", EVALUATE:"", TRIAL:"y", ADOPT:"", HOLD:"", DATE:"14-6-2017", DETAILS:"VoIP - trying out"},
		{TECH:"GoogleMail", CAT:"service", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"", EVALUATE:"", TRIAL:"", ADOPT:"", HOLD:"y", DATE:"2-7-2016", DETAILS:"use alot"},
		{TECH:"snow leopard", CAT:"platform", PLAN_FOR_REMOVAL:"YES", NO_NEW_USE:"", EVALUATE:"", TRIAL:"", ADOPT:"", HOLD:"", DATE:"2-8-2011", DETAILS:"On older machines - phasing out"},
		{TECH:"VirtualBox", CAT:"platform", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"", EVALUATE:"", TRIAL:"", ADOPT:"", HOLD:"y", DATE:"14-6-2012", DETAILS:"VM - still using alot"},
		{TECH:"WindowsXP", CAT:"platform", PLAN_FOR_REMOVAL:"y", NO_NEW_USE:"", EVALUATE:"", TRIAL:"", ADOPT:"", HOLD:"", DATE:"2-7-2002", DETAILS:"OS - older machines - replacing"},
		{TECH:"El Capitan", CAT:"platform", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"", EVALUATE:"", TRIAL:"", ADOPT:"y", HOLD:"", DATE:"2-8-2017", DETAILS:"OSX - newest in use at moment"},
		{TECH:"Lua", CAT:"app", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"", EVALUATE:"y", TRIAL:"", ADOPT:"", HOLD:"", DATE:"14-6-2017", DETAILS:"coding - experimenting"},
		{TECH:"php", CAT:"app", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"y", EVALUATE:"", TRIAL:"", ADOPT:"", HOLD:"", DATE:"2-7-2016", DETAILS:"coding - replacing with other languages"},
		{TECH:"asp.net", CAT:"platform", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"", EVALUATE:"", TRIAL:"", ADOPT:"", HOLD:"y", DATE:"14-6-2017", DETAILS:"coding - still using alot"},
		{TECH:"julia", CAT:"app", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"", EVALUATE:"", TRIAL:"", ADOPT:"y", HOLD:"", DATE:"2-7-2016", DETAILS:"coding - trying out"},
		{TECH:"haskell", CAT:"app", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"", EVALUATE:"y", TRIAL:"", ADOPT:"", HOLD:"", DATE:"2-8-2017", DETAILS:"coding - good potential"},
		{TECH:"Red Hat", CAT:"platform", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"", EVALUATE:"", TRIAL:"y", ADOPT:"", HOLD:"", DATE:"14-6-2017", DETAILS:"Linux OS - trying out"},
		{TECH:"mountain lion", CAT:"platform", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"y", EVALUATE:"", TRIAL:"", ADOPT:"", HOLD:"", DATE:"2-7-2016", DETAILS:"OSX - still using on some older machines"},
		{TECH:"BT cloud", CAT:"service", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"", EVALUATE:"y", TRIAL:"", ADOPT:"", HOLD:"", DATE:"2-8-2017", DETAILS:"cloud storage - trying out"},
		{TECH:"VLC", CAT:"app", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"", EVALUATE:"", TRIAL:"", ADOPT:"", HOLD:"y", DATE:"14-6-2017", DETAILS:"media player - good for viewing camera footage"},
		{TECH:"MeshLab", CAT:"app", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"", EVALUATE:"", TRIAL:"y", ADOPT:"", HOLD:"", DATE:"14-6-2017", DETAILS:"CAD and STL software - trying out"},
		{TECH:"Google+", CAT:"service", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"", EVALUATE:"", TRIAL:"", ADOPT:"", HOLD:"y", DATE:"2-7-2016", DETAILS:"keep for now"},
		{TECH:"Python", CAT:"app", PLAN_FOR_REMOVAL:"y", NO_NEW_USE:"", EVALUATE:"", TRIAL:"", ADOPT:"", HOLD:"", DATE:"2-8-2017", DETAILS:"Coding - phasing out"},
		{TECH:"CentOS", CAT:"platform", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"", EVALUATE:"", TRIAL:"", ADOPT:"", HOLD:"y", DATE:"14-6-2017", DETAILS:"Linux OS - still using"},
		{TECH:"Windows95", CAT:"platform", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"", EVALUATE:"", TRIAL:"", ADOPT:"", HOLD:"", DATE:"2-7-2002", DETAILS:""},
		{TECH:"Windows13", CAT:"platform", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"", EVALUATE:"y", TRIAL:"", ADOPT:"", HOLD:"", DATE:"2-8-2017", DETAILS:"OS - new - try out.."},
		{TECH:"flash", CAT:"app", PLAN_FOR_REMOVAL:"y", NO_NEW_USE:"", EVALUATE:"", TRIAL:"", ADOPT:"", HOLD:"", DATE:"14-6-2017", DETAILS:"coding - replacing, no longer using"},
		{TECH:"3Design", CAT:"app", PLAN_FOR_REMOVAL:"y", NO_NEW_USE:"", EVALUATE:"", TRIAL:"", ADOPT:"", HOLD:"", DATE:"2-7-2016", DETAILS:"CAD software - no longer using"},
		{TECH:"Photoshop", CAT:"app", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"", EVALUATE:"", TRIAL:"", ADOPT:"", HOLD:"y", DATE:"14-6-2017", DETAILS:"image editing - always using"},
		{TECH:"FileZilla", CAT:"service", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"", EVALUATE:"", TRIAL:"", ADOPT:"", HOLD:"y", DATE:"2-7-2016", DETAILS:"FTP - stable, useful"},
		{TECH:"ZAP", CAT:"app", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"", EVALUATE:"", TRIAL:"", ADOPT:"y", HOLD:"", DATE:"2-8-2017", DETAILS:"Proxy - useful tool"},

		{TECH:"Parallels", CAT:"platform", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"", EVALUATE:"y", TRIAL:"", ADOPT:"", HOLD:"", DATE:"2-8-2017", DETAILS:"VM - trying out"},
		{TECH:"VMWare", CAT:"platform", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"y", EVALUATE:"", TRIAL:"", ADOPT:"", HOLD:"", DATE:"14-6-2017", DETAILS:"VM - not using as much"},
		{TECH:"Windows Virtual PC", CAT:"platform", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"y", EVALUATE:"", TRIAL:"", ADOPT:"", HOLD:"", DATE:"14-6-2017", DETAILS:"not using"},
		{TECH:"Opera", CAT:"service", PLAN_FOR_REMOVAL:"y", NO_NEW_USE:"", EVALUATE:"", TRIAL:"", ADOPT:"", HOLD:"", DATE:"2-7-2016", DETAILS:"Browser - hardly use"},
		{TECH:"Netscape", CAT:"service", PLAN_FOR_REMOVAL:"y", NO_NEW_USE:"", EVALUATE:"", TRIAL:"", ADOPT:"", HOLD:"", DATE:"2-8-2017", DETAILS:"Browser - not needed"},
		{TECH:"iTunes", CAT:"service", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"", EVALUATE:"y", TRIAL:"", ADOPT:"", HOLD:"", DATE:"14-6-2017", DETAILS:"music and apps"},
		{TECH:"Adobe Acrobat", CAT:"service", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"y", EVALUATE:"", TRIAL:"", ADOPT:"", HOLD:"", DATE:"2-7-2002", DETAILS:"file reader and editor"},
		{TECH:"Wacom bamboo", CAT:"service", PLAN_FOR_REMOVAL:"y", NO_NEW_USE:"", EVALUATE:"", TRIAL:"", ADOPT:"", HOLD:"", DATE:"2-8-2017", DETAILS:"graphic tablet software - not using much"},
		{TECH:"lockLizard", CAT:"service", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"y", EVALUATE:"", TRIAL:"", ADOPT:"", HOLD:"", DATE:"14-6-2017", DETAILS:"file reader - haven't used for ages"},
		{TECH:"Xcode", CAT:"platform", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"y", EVALUATE:"", TRIAL:"", ADOPT:"", HOLD:"", DATE:"2-7-2016", DETAILS:"for iPhone app building - no using"},
		{TECH:"XAMPP", CAT:"platform", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"", EVALUATE:"", TRIAL:"", ADOPT:"y", HOLD:"", DATE:"14-6-2017", DETAILS:"virtual server - use alot"},
		{TECH:"awk", CAT:"service", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"", EVALUATE:"y", TRIAL:"", ADOPT:"", HOLD:"", DATE:"2-7-2016", DETAILS:"terminal scripting - put in service to make up the dots"},
		{TECH:"sed", CAT:"platform", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"", EVALUATE:"", TRIAL:"y", ADOPT:"", HOLD:"", DATE:"2-8-2017", DETAILS:"terminal scripting - put in platform to make up the dots"},
		{TECH:"nano", CAT:"service", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"", EVALUATE:"", TRIAL:"y", ADOPT:"", HOLD:"", DATE:"2-7-2016", DETAILS:"terminal file editor - easy to use"},
		{TECH:"emacs", CAT:"platform", PLAN_FOR_REMOVAL:"", NO_NEW_USE:"", EVALUATE:"", TRIAL:"", ADOPT:"y", HOLD:"", DATE:"2-8-2017", DETAILS:"terminal file editor - favourite editor"}
	];

